---
- name: Update and reboot
  # note: your 'hosts' section will likely be different.
  hosts: ansi-node1
  gather_facts: no
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
      
    - name: Reboot servers
      reboot:
        pre_reboot_delay: 5
        msg: "!!!Attention, server will be rebooted in 90 seconds!!!"
